version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: cd enforce_codeowners && docker build . -t dodo
      - run: docker run -e GITHUB_TOKEN=$GITHUB_TOKEN dodo


workflows:
   version: 2
   build:
     jobs:
       - build
   nightly:
     triggers:
       - schedule:
           cron: "*/5 * * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build