version: 2
jobs:
  test:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          command: |
            cd enforce_codeowners
            docker build . -t dodo
            docker run dodo
